### ISSUE TITLE
Out of Memory Error

### ISSUE THREAD

**Issue by stefan-jung** [dita-community/org.dita-community.qa#8]
I have a huge DITA project with hundreds of topics and keys. The publication runs 30 minutes and then crashes with an out of memory error on a Intel Core i5 laptop with 8GB RAM. I started the publication with `-Xmx4000m`, `-Xmx6000m`, `-Xmx8000m` but they all failed.

![outofmemory](https://cloud.githubusercontent.com/assets/3266567/11496760/9390e882-9814-11e5-93e5-aef07d851133.png)

**Comment by drmacro** [comment]
100s of topics and keys shouldn't cause any memory problem, certainly not during preprocessing. Are you sure your memory setting is actually being used?

Are you using OT 2.1.2? If so, probably worth upgrading to 2.2 and retrying--many preprocessing bugs have been fixed.

Another test is to try generating HTML using 1.8.5 and see if you get the same failure.

If you can't identify the cause, best to create a gist with a data set that can reproduce the failure.

**Comment by stefan-jung** [comment]
@drmacro, I extensively refactored our architecture in the meantime and now I have some other issues to solve firstly. Currently I cannot publish the QA at all, because it fails early due to the other reported issues. I'll come back to this one later and will then provide a test scenario.

**Comment by drmacro** [comment]
Looking at your report again, if the memory settings are being used then the cause is almost certainly an infinite loop somewhere. Saxon will report looping apply-templates so that's probably not the cause. Could also be an issue with the data tripping over a bug somewhere.

**Comment by bcolborn** [comment]
Stefan, I have encountered this before as well. What for me is a normal map works fine, but when I created a monster map (all the topics in my repository) it crashed like this. I spoke to @paqman23 about it and neither of us have any idea how to address it.

**Comment by stefan-jung** [comment]
I close this issue. We reworked the structure of our data and eliminated key-chains (Key-Maps that link to Key-Maps). The `qa` still does not work, but this is related to #9.
